import 'package:flutter/material.dart';
import 'package:flutter/material.dart';
import 'package:lettutor20120205/components/rating_bar.dart';

class ReviewGen {
  final String avatar;
  final String name;
  final String date;
  final String review;
  final double rating;

  ReviewGen({
    required this.avatar,
    required this.name,
    required this.date,
    required this.review,
    required this.rating,
  });
}

class ReviewGenList {
  final List<ReviewGen> reviewlist = [
    ReviewGen(
      avatar: "assets/images/r_ava1.jpg",
      name: "Haruka Sawamura",
      date: "Nov 23 2023",
      review:
          "LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY",
      rating: 3.5,
    ),
    ReviewGen(
      avatar: "assets/images/r_ava2.jpg",
      name: "Akame",
      date: "Nov 23 2023",
      review:
          "LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY",
      rating: 3,
    ),
    ReviewGen(
      avatar: "assets/images/r_ava3.jpg",
      name: "Goromi",
      date: "Nov 23 2023",
      review:
          "LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY",
      rating: 5,
    ),
    ReviewGen(
      avatar: "assets/images/r_ava4.jpg",
      name: "Kaoru Sayama",
      date: "Nov 23 2023",
      review:
          "LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY",
      rating: 1,
    ),
    ReviewGen(
      avatar: "assets/images/r_ava5.jpg",
      name: "Saeko Mukoda",
      date: "Nov 23 2023",
      review:
          "LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY",
      rating: 4.2,
    ),
    ReviewGen(
      avatar: "assets/images/r_ava6.jpg",
      name: "Eri Kamataki",
      date: "Nov 23 2023",
      review:
          "LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY LGD.NOTHINGTOSAY",
      rating: 2.1,
    ),
  ];
}
