import 'package:flutter/material.dart';
import 'package:lettutor20120205/components/tutor.dart';

class TutorList {
  final List<Tutor> tutorlist = [
    Tutor(
      name: "Kiryu Kazuma",
      avatar: "assets/images/ava1.png",
      quotes: "4th chairman of Tojo Clan",
      education: "Rush, Brawler, Beast and Dragon style",
      rating: 4.0,
      rating_count: 13,
      language: "Japanese",
      skill: "Dragon",
      nationality: "Japan",
      favorite: false,
    ),
    Tutor(
      name: "Joryu",
      avatar: "assets/images/ava3.jpg",
      quotes: "Daidoji Faction's Agent",
      education: "Dragon Style and Agent Style",
      rating: 5.0,
      rating_count: 3,
      language: "Japanese",
      skill: "Agent",
      nationality: "Japan",
      favorite: false,
    ),
    Tutor(
      name: "Kihei Hanawa",
      avatar: "assets/images/ava4.png",
      quotes: "Daidoji Faction's Agent",
      education: "Agent Style",
      rating: 4.6,
      rating_count: 1,
      language: "Japanese",
      skill: "Agent",
      nationality: "Japan",
      favorite: false,
    ),
    Tutor(
      name: "Taiga Saejima",
      avatar: "assets/images/ava5.png",
      quotes: "Saejima Family Patriarch",
      education: "Tiger Style",
      rating: 0,
      rating_count: 18,
      language: "Japanese",
      skill: "18-counts",
      nationality: "Japan",
      favorite: false,
    ),
    Tutor(
      name: "Daigo Dojima",
      avatar: "assets/images/ava6.png",
      quotes: "6th chairman of Tojo Clan",
      education: "Master of Charisma",
      rating: 5,
      rating_count: 30000,
      language: "Japanese",
      skill: "Charisma",
      nationality: "Japan",
      favorite: false,
    ),
    Tutor(
      name: "Ichiban Kasuga",
      avatar: "assets/images/ava7.png",
      quotes: "Hero - Former Arakawa Family Member",
      education: "RPG IRL",
      rating: 2.3,
      rating_count: 10,
      language: "Japanese",
      skill: "Hero",
      nationality: "Japan",
      favorite: false,
    ),
    Tutor(
      name: "Goro Majima",
      avatar: "assets/images/ava2.jpg",
      quotes: "Majima Family Patriarch",
      education: "Thug, Breaker, Slugger and MadDog style",
      rating: 3.1,
      rating_count: 99,
      language: "Japanese",
      skill: "Mad Dog",
      nationality: "Japan",
      favorite: false,
    ),
  ];
}
